### ISSUE TITLE
prop camera/models

### ISSUE THREAD

**Issue by forrestharty** [Vinzuerio/ph-enhanced#18]
There is serious issue with the prop camera, that I hear frequently from those that play on my server. Also, it seems like you might have done something that ruins a bit of the pointshop compatability. Until now, all pointshop models were working just fine, but from time to time they'll completely break - not with errors, but with the gray generic player model.

**Comment by Vinzuerio** [comment]
Can you tell us specific way what's with the prop camera problem, and also the 'grey' playermodel (and when that happen)? 

If you had a big player model with prop camera collision on (ph_prop_camera_collisions 1), this may cause a problem.

Another thing that there was supposed to be 'Grey' player model which that was part of easter egg (see: https://github.com/Vinzuerio/ph-enhanced/blob/master/gamemodes/prop_hunt/entities/entities/ph_luckyball/init.lua#L142 )

But if you found this really wrong with the player model issue, be sure to recheck your variable is correct, and also try to disable the custom playermodel selection (ph_use_custom_plmodel 0). Also try not messing up with 'GM:PlayerSetModel'.

**Comment by forrestharty** [comment]
Not exactly certain, but it might have to do with collision. Now that I look, I haven't seen any issues. And oh, yeah, I saw the luckyball thing. To be honest, the luckyball that causes the blank playermodel hasn't been really well received.

Something completely different that I have noticed, is if you shoot and press E at the same time, you take no damage and you use no ammo.

**Comment by daunknownman2010** [comment]
If the player.mdl model is too annoying for you, it's easy to add a convar to disable easter eggs that do affect player(s) in the next version or so. It's under Wolvin's investigation though so it's up to what he decides to do.

**Comment by Vinzuerio** [comment]
Hmm... from what I have investigate, none of these happen but, there's might be:

- Be sure to check with your addons that may conflicting to the gamemode. I suspect like Enhanced Player Models addons and other "Forced" addons to set playermodel causes this to break.
- If you're using Pointshop 1 and modify the PlayerSetModel (or) modifying Player model at spawn, it is suggest by giving a timer instead having to set them immediately on spawn (since pointshop has 1 second delay for applying player's stuff)
- Lastly, if you are having issues when Pressing E while shooting but doesn't do any damage, it seems to be related to the network prediction issue, where you thinking you are actually still shooting at the props but the damage hasn't been registered on serverside yet. It has been mentioned on Garry's mod issues in while 2015 ago.
