### ISSUE TITLE
No Maps appear in the MapVote

### ISSUE THREAD

**Issue by Moonblaze1995** [Vinzuerio/ph-enhanced#2]
Hello,

I noticed earlier today, while updating my pointshop, after I restarted my server, the map list, that appears in the mapvote system slowly started to disappear. Over time, the list of maps got down to 1 or 2, and was there for awhile, but now has gone down to 0. I have already ensured that I removed any duplicate files from the Steam Workshop, as well as ensuring that I removed the fretta mapvote system, as I assume I no longer need it. Is this a good presumption? or is it still dependent on the fretta mapvote?

If you wouldn't mind getting back to me at your earliest convenience, I would be very much appreciative.

I have worked desperately the last 2.5 hours, to try and figure out what my issue is. But to no avail, I hadn't found any solutions.

Thanks,
Moonblaze
Boundless Knights Server Administrator
admin@boundlessknights.com

**Comment by Moonblaze1995** [comment]
I talked with D4UNKNOWN, said that he doesn't know much about the issue, asked about any LUA errors, I didn't see any but I figured I would post my server log when launching the server.
[console.txt](https://github.com/Vinzuerio/ph-enhanced/files/538034/console.txt)

**Comment by Vinzuerio** [comment]
http://project.wolvindra.net/phe_faq/#game_ConVar_mapvote

@Moonblaze1995 You could use "mv_cooldown", "mv_mapbeforerevote" and "mv_allowcurmap" sets to 0 to disable map vote Cooldowns.

**Comment by Moonblaze1995** [comment]
I have opened sh_mapvote.lua changed EnableCooldown to false, AllowCurrentMap to True, and MapsBeforeRevote to 0, and it still didn't work.

**Comment by Moonblaze1995** [comment]
I decided I would try a fresh install of garrysmod and all of my stuff that goes with it, and it works now. I wish I could've figured out the issue, but atleast it works, I appreciate the help thanks.

**Comment by Vinzuerio** [comment]
No problem! make sure you did check that you may have subscribed the Existing Mapvote or other mapvote system, which is may override the current mapvote that ships from this gamemode.

**Comment by aznninja5996** [comment]
I'd like to note that I am having the same issue, but would prefer to not have to wipe my server, for it has run for 3.5 years now and has a fairly good reputation.

**Comment by aznninja5996** [comment]
Okay! So I fixed my issue.
What I did was go around searching for files and folders that dealt with the fretta gamemode and deleted/replaced them with a brand new copy from this respiratory. I still had problems with it.... So I did a bit more investigating and found that the mapvote system stores its data in the "data" folder. Deleting this (like clearing cache) made all of my maps reappear. Right now, I have the issue with not being able to specify the maps that should be shown, such as the gm_ maps. I'm looking into it again because all of my configs specify the map types, but gm_ still appears. I could just ignore this and delete the gm_ maps, but I'd like to resolve it now rather than run into other issues in the future. I will report back is I find any new information. I'd also like to not that I noticed the "Close" button was removed from the team selection when initially joining in the recent update, but was still appearing on mine before I deleted the "mapvote" folder in my "data" folder.

**Comment by Moonblaze1995** [comment]
@aznninja5996 

Looking at the documentation page, everything was moved to Console Variables,

I would type "mv_mapprefix" in console and see what says it. That is how I ultimately got just Prophunt Maps to appear.

**Comment by aznninja5996** [comment]
Yeah, I think it was getting confused between the old residual files and new files. So, in the end, I search from the ends of the earth for anything that included the mapvote system and deleted them. Once I did that, I deleted the fretta and prop_hunt gamemode and reinstalled the files from this respiratory. That is how I fixed my problem. But to respond to your given task, I did do that at the start to see if it were my configuration files not being set up right, but it displayed exactly as my config stated. This led me to believe it was a file causing chaos. So that's when I did what I mentioned earlier. During the process, I also found that a line of code could have possibly been wrong, so I changed it on my end and opened a discussion on the GitHub to inform the devs.
