### ISSUE TITLE
Props gravity problem

### ISSUE THREAD

**Issue by lucas2107** [Vinzuerio/ph-enhanced#23]
Hi,

There is a big problem with the gravity of props.
My players complain about this problem: When you're in props, and you get something in your hands, if you touch someone with this, there is 1 chance of 4 to die.

Is it possible to investigate?

**Comment by Vinzuerio** [comment]
I assume what they're holding is bigger than it's prop?

**Comment by lucas2107** [comment]
For example, i was a barrel, and he killed me ( one shot ) with a barrel :/
It's happening with all props

**Comment by Vinzuerio** [comment]
Yeah it's due to new EntityTakeDamage which Player's damage are now being redirected to the "prop" entity, which sometimes if you are in same team, it may cause a _Friendly Fire_.

Will do the fix very soon.

(However, you may get killed from hunters if they used props and try to smash you with it. This should be normal behaviour since it's intended for killing props)

**Comment by lucas2107** [comment]
Okey, thanks ^^

**Comment by Vinzuerio** [comment]
Updated. Check on the main repository or Reclone the gamemode. it should fixes the problem for now
