### ISSUE TITLE
Idea: Custom Hulls

### ISSUE THREAD

**Issue by Jonpopnycorn** [Vinzuerio/ph-enhanced#32]
In the file the data can be placed something like this (kinda like the TTT custom respawn file)

[Prop Model] [Min Vector - X,Y,Z] [Max Vector - X,Y,Z] [Duck Min Vector - X,Y,Z] [Duck Max Vector - X,Y,Z]
models/props_fairgrounds/giraffe.mdl -10 -10 0 10 10 10 -10 -10 0 10 10 8

or something like this (since we can just reuse [Min/Max Vector - X,Y])
[Prop Model] [Min Vector - X,Y,Z] [Max Vector - X,Y,Z] [Duck Hull - Z]
models/props_fairgrounds/giraffe.mdl -10 -10 0 10 10 10 8

Could be a solution for Maps with bad prop model hulls (Like the Giraffe prop on ph_gas_station), or even make certain props to be closer to the wall (Like the Heater on ph_office)

**Comment by Vinzuerio** [comment]
So assuming there is a map config file (let's say maps/ph_restaurant_2017.txt) which contains model data path including their custom hulls properties?

``
models/props_fairgrounds/giraffe.mdl -10 -10 0 10 10 10 8
models/other_models/models.mdl -1 -2 3 4 x x x x
``

How about using with KeyValues? (not mentioning using _json_)

I'd like to include this feature but I'm afraid that sometimes prop player do not update with their hulls properties due to player's 'laginess' (but that shouldn't be happen too often anyway), or this can be caused by Server's side bad Game content mounting.

I'll try to figure this out later

**Comment by Vinzuerio** [comment]
update

Several map (especially un-optimised maps) causing to make a bad collision bounds to happen. if it forced to change, it may cause weird behaviour which server needs to be restarted.

**Comment by Vinzuerio** [comment]
Update
This will be reworked on revision B updates.

Notice that several maps do not have a proper bounding box but so it is good idea having this to set up manually.

**Comment by Vinzuerio** [comment]
Expect on Revision C to get this Custom Hulls worked.

**Comment by Vinzuerio** [comment]
Revision C has been updated. The feature also has been added.
See on this  topic on how to customize them:

https://project.wolvindra.net/phe/new/faq/?dir=Methods&gettopic=Customize_Prop_Hull
