### ISSUE TITLE
Kleiner Spawning in X 0 Z 0

### ISSUE THREAD

**Issue by lucas2107** [Vinzuerio/ph-enhanced#39]
Hi,

A kleiner is spawning on all map at coords X 0 & Z 0.

**Comment by daunknownman2010** [comment]
This issue is possibly caused by the client-side prop not being updated properly. This is the case when something overrides the Think() function on the client, or the variable to determine better prop movement is not updated properly. It could potentially be a lua script causing it to go off.

As of now, this is potentially not an issue on the new 14j-staging branch which completely scraps the client-side model and makes use of the server-side ph_prop entity instead (with SetRenderOrigin applied). If SetRenderOrigin is not applied to the ph_prop entity, it'll fallback to the server-side movement which should prevent the whole issue of the prop model not following or updating properly on your screen (just lags behind instead).

**Comment by lucas2107** [comment]
Problem solved with your last update ^^
