### ISSUE TITLE
Enhancement for hitbox of props. And a question

### ISSUE THREAD

**Issue by Darkouille81** [Vinzuerio/ph-enhanced#51]
Hello there
I'm just here to give what I use for the hitbox of the props (I didn't try the new one)
In GM:PlayerSetModel(pl),  when setting the player_model I use "models/props_phx/misc/gibs/egg_piece5.mdl"
Instead of the new model. I didn't get any problems about blood or props that doesn't take bullets
Here is the size in screen (left is the plate, right is the model above) : https://cdn.discordapp.com/attachments/293009398865854466/398198275490054155/20180103203528_1.jpg

And I have a question about props who can change into destroyed parts of other props
How can I disable it ?
Do I need to ban all parts that props split into ?

**Comment by Vinzuerio** [comment]
This may consider how thin the collision of the model has and also this may also works for non-colliding models that should accept directly to the ph_prop's Model.
In previous version of PH:E, the model was used from Antlion Gib, but the bounding box are kinda messed up so it just doesn't take any bullets. [By adding this code](https://github.com/Vinzuerio/ph-enhanced/blob/14j-staging/gamemodes/prop_hunt/gamemode/init.lua#L214), this does take damage , however by using recent model, it may sometime does not take any damage info.

Probably I'll try another test for the model that set for props and which one should be better for it.

You can manually disables the model by providing the model path under `data/prop_hunt-enhanced/prop_playermodel_bans.txt`.
You can simply add the list for example:
```
[
     "models/player",
     "models/props_phx/misc/gibs/egg_piece1.mdl",
     "models/props_phx/misc/gibs/egg_piece2.mdl",
     "models/props_phx/misc/gibs/egg_piece3.mdl",
     "models/props_phx/misc/gibs/egg_piece4.mdl",
     "models/pieces_models_etc.mdl"
]
```

**Comment by Darkouille81** [comment]
Well thanks you for your answer, I did not explain myself well for my question, I explain again :
In a older version of the gamemode, the player in props team can't change into pieces of destroyed props.

Example :
A hunter destroy a table, guys in props team can change into a little piece of the table.
A hunter destroy a dustbin, props can change into the parts the dustbin is splited into, like a ball of paper, a empty can.
If a guy in props team destroy a beer bottle, he can change into pieces of it, so in the breaked top of the bottle and the body of the bottle.

I'm hopping i'm clear now xD
I will ban "parts/pieces" of props if i can't disable turning into them. (don't close the issue, if I need to ban all props I will drop here all the pieces of the props.)

Thanks you for taking some time !

**Comment by Vinzuerio** [comment]
Hold on, are you on Singleplayer or Listen Server with someone? (Not to mention in Dedicated Server)

First thing about prop pieces from a destroyed props:
In Dedicated Server, currently it is impossible and there is no way to capable to turn into destroyed props pieces, or even to get the Temporary Entity from it (even though the GMod itself does not provide a code for player pickup debris entity in multiplayer). The pieces are ClientSide Debris entities which this are impossible to make for Multiplayer. however this can be done in Singleplayer. (since the debris itself coded by shared realm) If you really found out this was working on Listen Server, I'll have to look at it.

However, this must be done manually by making a prop break code into random pieces, and forces to server side pieces entities instead. However, there's a downside: Huge Performance Impact, so I don't recommend bother to do this.

also, it always works after you put the lists of props in that file. Should fixed the issue then.

**Comment by Vinzuerio** [comment]
Had to re-confirm that this may never happen during this new Gmod update, or perhaps the Debris was actually really occurs and can become as a destroyed pieces which actually you could possible tried on Singleplayer (not Multiplayer Listen Server) Mode. This never happen during on Multiplayer/Dedicated Server mode.

Perhaps you did used some addons that override the broken pieces (debris) into server-sided props entity, which is why the prop is able to disguise as a broken pieces.

Also, if the problem still occurs, Re-open the issue so I'll take the investigation on this.
