### ISSUE TITLE
Custom taunts displayed twice

### ISSUE THREAD

**Issue by lucas2107** [Vinzuerio/ph-enhanced#68]
Custom taunts are displayed twice.

Sound #X & the custom name.

**Comment by Vinzuerio** [comment]
Can you post the reproduce code for it?

**Comment by lucas2107** [comment]
I used the original code.

**Comment by Vinzuerio** [comment]
I was thought this might be caused by the sound that located under `sound/taunts/<team>_customs/` and having a same path will cause duplicated sound listing.

Did you changed the taunt scanner path under `sound/taunts/props` ?

If it still persist perhaps this require some `table.HasValue` checking to make sure they don't exists in the list, making it so to prevent duplicated.

**Comment by lucas2107** [comment]
I changed the path to sounds/soleria for taunts because i was always using it for taunts.

**Comment by Vinzuerio** [comment]
For some reason I could not reproduce the code even though I'm using different computer (current computer is died btw), but, i might have to investigate more in future.

**Comment by katawajojo** [comment]
I've also run into this game bug

**Comment by Vinzuerio** [comment]
Update has been launched, but it may still bugging or not. Report again if anything still persists

**Comment by Vinzuerio** [comment]
anyway, you could use this plugin instead:
https://github.com/Vinzuerio/taunt_scanner

it's a seperated version and made it as plugin. you can experience it by yourself since it's really apart from the gamemode.
