### ISSUE TITLE
Is this a proper iteration?

### ISSUE THREAD

**Issue by aznninja5996** [Vinzuerio/ph-enhanced#7]
Here: https://github.com/Vinzuerio/ph-enhanced/blob/master/gamemodes/fretta/gamemode/cl_selectscreen.lua

Starting at line 303

Shouldn't it be the other way around? Like

```
if (  IsValid( LocalPlayer() ) && LocalPlayer():Team() == TEAM_UNASSIGNED ) then
    TeamPanel:AddCancelButton()
end
```

Should look like

```
if (  IsValid( LocalPlayer() ) && LocalPlayer():Team() == ( TEAM_HUNTERS ||  TEAM_PROPS || TEAM_SPECTATOR ) then
    TeamPanel:AddCancelButton()
end
```

Wouldn't my modification make your statement, "Players can no longer close the Team Selection when joining the game," true?

Because in-game I am unable to close it when on a team, but able to close it when not on a team.

Or, you could just make it `LocalPlayer():Team() != TEAM_UNASSIGNED`

I think this is what you wanted, not sure, but I think so.

**Comment by Jonpopnycorn** [comment]
@aznninja5996 Yeah the code was meant to be `LocalPlayer():Team() != TEAM_UNASSIGNED` had typo

@Vinzuerio Never had a problem on a server with 10-38 players being unbalanced, had it set to where TEAM_UNASSIGNED couldn't close the Team Selection to reduce people asking "How do I join a team" because they wanted to close it on the start when joining. haha

**Comment by Vinzuerio** [comment]
That often happen, because it only checks for unassigned team that allows you to 'close' , but remain teams doesn't, which they had to force change teams to others so you can't cancel the team select screen.

You can remove specific team that you want to disable the 'close' button on specific team, but however I recommend this method instead.

Good to know if there was a typo, at least it seems solved for now
